# Generated by Django 5.2.1 on 2025-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='video_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.JSONField(),
        ),
    ]
